swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Sagrado Futebol
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /post:
    get:
      operationId: post.read_all
      tags:
        - Post
      summary: Read the entire set of post, sorted by last name
      description: Read the entire set of post, sorted by last name
      responses:
        200:
          description: Successfully read post set operation
          schema:
            type: array
            items:
              properties:
                post_id:
                  type: string
                  description: Id of the person
                fname:
                  type: string
                  description: First name of the person
                lname:
                  type: string
                  description: Last name of the person
                timestamp:
                  type: string
                  description: Creation/Update timestamp of the person

    post:
      operationId: post.create
      tags:
        - Post
      summary: Create a person
      description: Create a new person
      parameters:
        - name: post
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of person to create
              lname:
                type: string
                description: Last name of person to create
      responses:
        201:
          description: Successfully created person
          schema:
            properties:
              post_id:
                type: string
                description: Id of the person
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Creation/Update timestamp of the person record

  /post/{post_id}:
    get:
      operationId: post.read_one
      tags:
        - Post
      summary: Read one person
      description: Read one person
      parameters:
        - name: post_id
          in: path
          description: Id of the person to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read person from post data operation
          schema:
            type: object
            properties:
              post_id:
                type: string
                description: Id of the person
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Creation/Update timestamp of the person record

    put:
      operationId: post.update
      tags:
        - Post
      summary: Update a person
      description: Update a person
      parameters:
        - name: post_id
          in: path
          description: Id the person to update
          type: integer
          required: True
        - name: person
          in: body
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the post
      responses:
        200:
          description: Successfully updated post
          schema:
            properties:
              post_id:
                type: string
                description: Id of the person in the database
              fname:
                type: string
                description: First name of the person
              lname:
                type: string
                description: Last name of the person
              timestamp:
                type: string
                description: Creation/Update timestamp of the person record

    delete:
      operationId: post.delete
      tags:
        - Post
      summary: Delete a person from the post list
      description: Delete a person
      parameters:
        - name: post_id
          in: path
          type: integer
          description: Id of the post to delete
          required: true
      responses:
        200:
          description: Successfully deleted a post